### ISSUE TITLE
Queries regarding your library

### ISSUE THREAD

**Issue by Vignesh0619** [Bruno4l/SSD1306-EK-TM4C123GXL#1]
Hi bruno,
I was going through your SSD1306 library .It looks really helpful for my project but I have a few questions I wanna ask.
1.is this for a 128x64 display or for 128x32 display. Your code seems to be for a x64 module for the title says otherwise
2. is the data file correct and uncorrupted. Could you check that once
3. I also noticed that  in your ssd1306.h file you have defined variable  bitmap_t. But you have not used it anywhere from what I can see. Is that on purpose or is it an error.
4. Lastly is this library compatible with code composer studio

I am extremely thankful for your library and I am sorry if I was rude.I hope to hear back from you very soon.
-Vignesh

**Comment by Bruno4l** [comment]
Hi Vignesh
This project I developed as part of a college project, that was some time ago, but I'll try to help you.
1. this is for 128x32 but you can change the initialization sequence in `OLED_Init()` to 128x64
2. this file is corrupted, but it does not interfere with the functioning of the library
3. the bitmap_t type was defined but not used, so not an error
4. probably yes if you are using a TM4C123GXL, but if it is not compatible, you can change the functions `I2C_sendSingleByte(uint8_t slave_addr, char data)` and `I2C_sendMultipleBytes(uint8_t slave_addr, uint8_t numOfBytes, char by[])` to match your hardware

**Comment by Vignesh0619** [comment]
Hi bruno,

Thanks for the quick reply.

Vignesh
